fn main() {
    generate_tray_translations();
    embed_dotenv();
    write_app_permission();
    forbid_remote_capabilities();

    tauri_build::build();

    require_app_acl_manifest();
}

fn write_app_permission() {
    use std::fs;

    const SOURCE: &str = "src/lib.rs";
    const TARGET: &str = "permissions/app.toml";
    println!("cargo:rerun-if-changed={SOURCE}");

    let source = fs::read_to_string(SOURCE).expect("src/lib.rs is readable");
    let commands = registered_commands(&source);

    let mut out = String::from(
        "# Generated by build.rs from the collect_commands![...] list in src/lib.rs.\n\
         # Do not edit: it is rewritten on every build.\n\n\
         [[permission]]\n\
         identifier = \"app-commands\"\n\
         description = \"Every command this application registers. Capabilities grant it to the application's own pages only.\"\n\
         commands.allow = [\n",
    );
    for command in &commands {
        out.push_str(&format!("  \"{command}\",\n"));
    }
    out.push_str("]\n");

    if fs::read_to_string(TARGET).ok().as_deref() != Some(out.as_str()) {
        fs::create_dir_all("permissions").expect("permissions/ can be created");
        fs::write(TARGET, out).expect("permissions/app.toml can be written");
    }
}

fn registered_commands(source: &str) -> Vec<String> {
    const OPEN: &str = "collect_commands![";
    let start = source
        .find(OPEN)
        .expect("src/lib.rs contains collect_commands![...]")
        + OPEN.len();
    let end = start
        + source[start..]
            .find(']')
            .expect("collect_commands![...] is closed");

    let mut commands = Vec::new();
    for line in source[start..end].lines() {
        let entry = line.split("//").next().unwrap_or("").trim();
        for item in entry.split(',').map(str::trim).filter(|i| !i.is_empty()) {
            let is_path = item
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == ':');
            if !is_path {
                panic!(
                    "collect_commands![...] contains {item:?}, which build.rs cannot read as a \
                     command path. Teach registered_commands() about it: a command that is \
                     skipped here is rejected at run time."
                );
            }
            let name = item.rsplit("::").next().unwrap_or(item).to_string();
            if commands.contains(&name) {
                panic!("collect_commands![...] lists {name} twice");
            }
            commands.push(name);
        }
    }
    if commands.is_empty() {
        panic!("collect_commands![...] is empty: no command would be allowed at run time");
    }
    commands
}

fn forbid_remote_capabilities() {
    use std::fs;

    println!("cargo:rerun-if-changed=capabilities");
    for entry in fs::read_dir("capabilities")
        .expect("capabilities/ exists")
        .flatten()
    {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let text = fs::read_to_string(&path).expect("capability file is readable");
        let value: serde_json::Value =
            serde_json::from_str(&text).expect("capability file is valid JSON");
        let capabilities = match &value {
            serde_json::Value::Object(map) if map.contains_key("capabilities") => {
                map["capabilities"].as_array().cloned().unwrap_or_default()
            }
            other => vec![other.clone()],
        };
        for capability in capabilities {
            if capability.get("remote").is_some() {
                panic!(
                    "{} grants commands to a remote origin (\"remote\"). No page other than \
                     the application's own may call commands.",
                    path.display()
                );
            }
        }
    }
}

fn require_app_acl_manifest() {
    use std::fs;
    use std::path::Path;

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let path = Path::new(&out_dir).join("acl-manifests.json");
    let text = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "tauri-build did not write {}: {e}. The app ACL manifest cannot be confirmed.",
            path.display()
        )
    });
    let manifests: serde_json::Value =
        serde_json::from_str(&text).expect("acl-manifests.json is valid JSON");
    let has_app_commands = manifests
        .get("__app-acl__")
        .and_then(|app| app.get("permissions"))
        .and_then(|permissions| permissions.get("app-commands"))
        .is_some();
    if !has_app_commands {
        panic!(
            "the app ACL manifest is missing from {}. Without it Tauri does not check which \
             origin calls an application command.",
            path.display()
        );
    }
}

fn embed_dotenv() {
    use std::fs;
    use std::path::Path;

    const EMBED_KEYS: &[&str] = &[
        "ANONEN_CLOUD_URL",
        "ANONEN_SUPABASE_URL",
        "ANONEN_SUPABASE_ANON_KEY",
        "ANONEN_SEALED_REQUIRED",
    ];

    let env_path = Path::new(".env");
    println!("cargo:rerun-if-changed=.env");

    let content = match fs::read_to_string(env_path) {
        Ok(c) => c,
        Err(_) => {
            embed_accepted_digests(false);
            return;
        }
    };

    let mut sealing_required = true;

    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            let key = key.trim();
            let value = value.trim();
            match key {
                "ANONEN_ACCEPTED_IMAGE_DIGESTS" if !value.is_empty() => panic!(
                    "ANONEN_ACCEPTED_IMAGE_DIGESTS moved out of .env: the accepted \
                     list is the committed file src-tauri/accepted-digests.txt \
                     (one digest per line). Delete this line from .env."
                ),

                "ANONEN_SEALED_REQUIRED" => {
                    sealing_required =
                        !matches!(value.to_ascii_lowercase().as_str(), "0" | "false" | "no")
                }
                _ => {}
            }
            if EMBED_KEYS.contains(&key) && !value.is_empty() {
                println!("cargo:rustc-env={}={}", key, value);
            }
        }
    }

    let plaintext_compiled = std::env::var_os("CARGO_FEATURE_PLAINTEXT_DEV").is_some();
    if !plaintext_compiled && !sealing_required {
        println!(
            "cargo:warning=ANONEN_SEALED_REQUIRED=0 has no effect: the plaintext route is \
             not compiled in (add --features plaintext-dev for a plaintext dev build)"
        );
    }
    embed_accepted_digests(sealing_required || !plaintext_compiled);
}

fn embed_accepted_digests(sealing_required: bool) {
    use std::fs;

    const FILE: &str = "accepted-digests.txt";
    println!("cargo:rerun-if-changed={FILE}");

    let content = fs::read_to_string(FILE).unwrap_or_default();
    let digests: Vec<&str> = content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .collect();

    for digest in &digests {
        let hex = digest.strip_prefix("sha256:").unwrap_or("");
        if hex.len() != 64 || !hex.chars().all(|c| c.is_ascii_hexdigit()) {
            panic!(
                "{FILE} contains {digest:?}, which is not `sha256:` + 64 hex. \
                 A misspelt digest matches nothing, and a build that matches \
                 nothing never transcribes."
            );
        }
    }

    if digests.is_empty() {
        if sealing_required {
            panic!(
                "src-tauri/{FILE} lists no digest. An empty list accepts no \
                 enclave at all (contract V13), so this build would install and \
                 never transcribe once. Put the running image's digest in it \
                 (`sha256:` + 64 hex, one per line), or set \
                 ANONEN_SEALED_REQUIRED=false in .env for a plaintext \
                 development build."
            );
        }
        return;
    }

    println!(
        "cargo:rustc-env=ANONEN_ACCEPTED_IMAGE_DIGESTS={}",
        digests.join(",")
    );
}

fn generate_tray_translations() {
    use std::collections::BTreeMap;
    use std::fs;
    use std::path::Path;

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let locales_dir = Path::new("../src/i18n/locales");

    println!("cargo:rerun-if-changed=../src/i18n/locales");

    let mut translations: BTreeMap<String, serde_json::Value> = BTreeMap::new();

    for entry in fs::read_dir(locales_dir).unwrap().flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }

        let lang = path.file_name().unwrap().to_str().unwrap().to_string();
        let json_path = path.join("translation.json");

        println!("cargo:rerun-if-changed={}", json_path.display());

        let content = fs::read_to_string(&json_path).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&content).unwrap();

        if let Some(tray) = parsed.get("tray").cloned() {
            translations.insert(lang, tray);
        }
    }

    let english = translations.get("en").unwrap().as_object().unwrap();
    let fields: Vec<_> = english
        .keys()
        .map(|k| (camel_to_snake(k), k.clone()))
        .collect();

    let mut out = String::from(
        "// Auto-generated from src/i18n/locales/*/translation.json - do not edit\n\n",
    );

    out.push_str("#[derive(Debug, Clone)]\npub struct TrayStrings {\n");
    for (rust_field, _) in &fields {
        out.push_str(&format!("    pub {rust_field}: String,\n"));
    }
    out.push_str("}\n\n");

    out.push_str(
        "pub static TRANSLATIONS: Lazy<HashMap<&'static str, TrayStrings>> = Lazy::new(|| {\n",
    );
    out.push_str("    let mut m = HashMap::new();\n");

    for (lang, tray) in &translations {
        out.push_str(&format!("    m.insert(\"{lang}\", TrayStrings {{\n"));
        for (rust_field, json_key) in &fields {
            let val = tray.get(json_key).and_then(|v| v.as_str()).unwrap_or("");
            out.push_str(&format!(
                "        {rust_field}: \"{}\".to_string(),\n",
                escape_string(val)
            ));
        }
        out.push_str("    });\n");
    }

    out.push_str("    m\n});\n");

    fs::write(Path::new(&out_dir).join("tray_translations.rs"), out).unwrap();

    println!(
        "cargo:warning=Generated tray translations: {} languages, {} fields",
        translations.len(),
        fields.len()
    );
}

fn camel_to_snake(s: &str) -> String {
    s.chars()
        .enumerate()
        .fold(String::new(), |mut acc, (i, c)| {
            if c.is_uppercase() && i > 0 {
                acc.push('_');
            }
            acc.push(c.to_lowercase().next().unwrap());
            acc
        })
}

fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}
