use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};

use log::{error, info};
use objc2::rc::Retained;
use objc2::{define_class, msg_send, AnyThread, DefinedClass};
use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::{NSArray, NSInteger, NSObject, NSString};
use tauri::{AppHandle, Manager};
use tauri_plugin_clipboard_manager::ClipboardExt;

use super::{evaluate, send_chord, TxState, WaitDecision};
use crate::clipboard::send_return_key;
use crate::input::EnigoState;
use crate::settings::{AutoSubmitKey, ClipboardHandling, PasteMethod};

const CONCEALMENT_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

pub struct ProviderIvars {
    state: Arc<Mutex<TxState>>,
    text: String,
}

define_class!(

    #[unsafe(super(NSObject))]
    #[name = "HandyPasteProvider"]
    #[ivars = ProviderIvars]
    pub struct HandyPasteProvider;

    impl HandyPasteProvider {

        #[unsafe(method(pasteboard:provideDataForType:))]
        fn pasteboard_provide_data_for_type(&self, pasteboard: &NSPasteboard, data_type: &NSString) {
            let ivars = self.ivars();

            let is_text = unsafe { data_type.isEqualToString(NSPasteboardTypeString) };

            if is_text {
                if let Ok(mut state) = ivars.state.lock() {
                    state.record_receipt(Instant::now());
                }
            }
            let payload = if is_text {
                NSString::from_str(&ivars.text)
            } else {

                NSString::from_str("")
            };
            let _ = pasteboard.setString_forType(&payload, data_type);
        }

        #[unsafe(method(pasteboardChangedOwner:))]
        fn pasteboard_changed_owner(&self, _pasteboard: &NSPasteboard) {
            if let Ok(mut state) = self.ivars().state.lock() {
                state.ownership_lost = true;
            }
        }
    }
);

impl HandyPasteProvider {
    fn new(state: Arc<Mutex<TxState>>, text: String) -> Retained<Self> {
        let this = Self::alloc().set_ivars(ProviderIvars { state, text });
        unsafe { msg_send![super(this), init] }
    }
}

struct MacPending {
    state: Arc<Mutex<TxState>>,
    saved_text: Option<String>,
    saved_image: Option<tauri::image::Image<'static>>,
    change_count: NSInteger,
    provider: Option<Retained<HandyPasteProvider>>,
    auto_submit: bool,
    auto_submit_key: AutoSubmitKey,

    preserve_transcript: bool,

    transcript: String,
    settled: bool,
}

static PENDING: Mutex<Option<Arc<Mutex<MacPending>>>> = Mutex::new(None);

fn settle(
    pending: &Arc<Mutex<MacPending>>,
    app_handle: &AppHandle,
    enigo: Option<&mut enigo::Enigo>,
) {
    let mut p = match pending.lock() {
        Ok(p) => p,
        Err(_) => return,
    };
    if p.settled {
        return;
    }
    p.settled = true;

    let (receipt_seen, ownership_lost) = match p.state.lock() {
        Ok(st) => (st.any_receipt_after_injection(), st.ownership_lost),
        Err(_) => (false, true),
    };

    if p.auto_submit && receipt_seen {
        match enigo {
            Some(e) => {
                let _ = send_return_key(e, p.auto_submit_key);
            }
            None => {
                if let Some(enigo_state) = app_handle.try_state::<EnigoState>() {
                    if let Ok(mut e) = enigo_state.0.lock() {
                        let _ = send_return_key(&mut e, p.auto_submit_key);
                    }
                }
            }
        }
    }

    let still_ours =
        !ownership_lost && NSPasteboard::generalPasteboard().changeCount() == p.change_count;
    if !still_ours {
        info!("[reliable-paste] clipboard changed externally; leaving it untouched");
    } else if p.preserve_transcript {
        let _ = app_handle.clipboard().write_text(&p.transcript);
        info!("[reliable-paste] left transcript on clipboard as plain text");
    } else {
        let clipboard = app_handle.clipboard();
        if let Some(text) = &p.saved_text {
            let _ = clipboard.write_text(text);
        } else if let Some(image) = &p.saved_image {
            let _ = clipboard.write_image(image);
        } else {
            let _ = clipboard.clear();
        }
        info!("[reliable-paste] restored previous clipboard");
    }

    p.provider = None;
}

fn flush_pending(app_handle: &AppHandle, enigo: &mut enigo::Enigo) {
    let previous = match PENDING.lock() {
        Ok(mut slot) => slot.take(),
        Err(_) => None,
    };
    if let Some(previous) = previous {
        settle(&previous, app_handle, Some(enigo));
    }
}

fn spawn_waiter(pending: Arc<Mutex<MacPending>>, app_handle: AppHandle) {
    thread::spawn(move || {
        let outcome = loop {
            thread::sleep(Duration::from_millis(15));
            let (decision, state_snapshot) = {
                let p = match pending.lock() {
                    Ok(p) => p,
                    Err(_) => return,
                };
                if p.settled {
                    return;
                }
                let result = match p.state.lock() {
                    Ok(st) => {
                        let now = Instant::now();
                        let snapshot = (
                            st.any_receipt_after_injection(),
                            st.ownership_lost,
                            st.injection_failed,
                        );
                        (evaluate(&st, now), snapshot)
                    }
                    Err(_) => return,
                };
                result
            };
            if let WaitDecision::Finish = decision {
                break state_snapshot;
            }
        };

        let (receipt_seen, ownership_lost, injection_failed) = outcome;
        if ownership_lost {
            info!("[reliable-paste] settling: clipboard ownership lost");
        } else if receipt_seen {
            info!("[reliable-paste] settling: reads went quiet");
        } else if injection_failed {
            info!("[reliable-paste] settling: chord injection failed, restoring quickly");
        } else {
            info!("[reliable-paste] settling: no read within timeout, restoring anyway");
        }

        let pending_for_finish = pending.clone();
        let app_for_finish = app_handle.clone();
        let _ = app_handle.run_on_main_thread(move || {
            settle(&pending_for_finish, &app_for_finish, None);
            if let Ok(mut slot) = PENDING.lock() {
                let is_us = slot
                    .as_ref()
                    .map(|current| Arc::ptr_eq(current, &pending))
                    .unwrap_or(false);
                if is_us {
                    *slot = None;
                }
            }
        });
    });
}

pub(super) fn run(
    text: &str,
    app_handle: &AppHandle,
    paste_method: &PasteMethod,
    enigo: &mut enigo::Enigo,
    auto_submit: bool,
    auto_submit_key: AutoSubmitKey,
    clipboard_handling: ClipboardHandling,
) -> Result<(), String> {
    flush_pending(app_handle, enigo);

    let clipboard = app_handle.clipboard();
    let saved_text = clipboard.read_text().ok().filter(|t| !t.is_empty());

    let saved_image = if saved_text.is_none() {
        clipboard.read_image().ok().map(|image| image.to_owned())
    } else {
        None
    };

    let state = Arc::new(Mutex::new(TxState::new()));
    let provider = HandyPasteProvider::new(state.clone(), text.to_string());
    let pasteboard = NSPasteboard::generalPasteboard();

    let mut types: Vec<Retained<NSString>> = Vec::with_capacity(1 + CONCEALMENT_TYPES.len());
    types.push(NSString::from_str("public.utf8-plain-text"));
    for t in CONCEALMENT_TYPES {
        types.push(NSString::from_str(t));
    }
    let types = NSArray::from_retained_slice(&types);

    let change_count: NSInteger =
        unsafe { msg_send![&*pasteboard, declareTypes: &*types, owner: &*provider] };
    if change_count <= 0 {
        return Err("declareTypes:owner: failed".to_string());
    }
    info!("[reliable-paste] published transcript as lazy promise (changeCount {change_count})");

    if let Ok(mut st) = state.lock() {
        st.injected_at = Some(Instant::now());
    }
    match send_chord(enigo, paste_method) {
        Ok(()) => {
            info!("[reliable-paste] paste chord sent ({paste_method:?})");
        }
        Err(e) => {
            if let Ok(mut st) = state.lock() {
                st.injection_failed = true;
            }
            error!("[reliable-paste] failed to send paste chord: {e}");
        }
    }

    let pending = Arc::new(Mutex::new(MacPending {
        state,
        saved_text,
        saved_image,
        change_count,
        provider: Some(provider),
        auto_submit,
        auto_submit_key,
        preserve_transcript: clipboard_handling == ClipboardHandling::CopyToClipboard,
        transcript: text.to_string(),
        settled: false,
    }));
    if let Ok(mut slot) = PENDING.lock() {
        *slot = Some(pending.clone());
    }
    spawn_waiter(pending, app_handle.clone());

    Ok(())
}
